### ISSUE TITLE
생성된 투두 우측에 수정 버튼과 삭제 버튼 UI 구현

### ISSUE THREAD

**Issue by yeon-kk** [yeon-kk/wanted-pre-onboarding-frontend#15]
### 요구사항
- TODO 우측에 수정버튼과 삭제 버튼을 만들어주세요
  - 수정 버튼에는 data-testid="modify-button" 속성을 부여해주세요
  - 삭제 버튼에는 data-testid="delete-button" 속성을 부여해주세요
<li>
  <label>
    <input type="checkbox" />
    <span>TODO 1</span>
  </label>
  <button data-testid="modify-button">수정</button>
  <button data-testid="delete-button">삭제</button>
</li>

### Tasks
- [x] `수정` 버튼 UI 구현
- [x] `수정` 버튼에 요구사항의 속성 부여
- [x] `삭제` 버튼 UI 구현
- [x] `수정` 버튼에 요구사항의 속성 부여
