### ISSUE TITLE
투두 삭제 버튼 클릭하면 해당 투두가 삭제되는 기능 구현

### ISSUE THREAD

**Issue by yeon-kk** [yeon-kk/wanted-pre-onboarding-frontend#16]
### 요구사항
- 투두 리스트의 삭제 기능을 구현해주세요
- 투두 리스트의 TODO 우측의 삭제버튼을 누르면 해당 아이템이 삭제되도록 해주세요

### Tasks
- [x] handleDeleteClick(index: string) 함수 생성
- [x] 인자로 받은 index를 splice(index,1) 메서드를 사용하여 배열에서 삭제
- [x] onClick 속성에 handleDeleteClick(index) 함수를 인자로 전달
