### ISSUE TITLE
요구사항 조건에 맞게 data-testedid 추가, Markup 순서 재배치

### ISSUE THREAD

**Issue by yeon-kk** [yeon-kk/wanted-pre-onboarding-frontend#29]
### Tasks
- [x] data-testid="signin-button"
- [x] data-testid="signup-button"
- [x] ![image](https://user-images.githubusercontent.com/86847564/216817139-9a20f9c5-0d7b-497f-a804-09531cffccf4.png)
- [x] ![image](https://user-images.githubusercontent.com/86847564/216817243-d8842216-b2ce-4ecf-9bdd-1a66d6110099.png)
