### ISSUE TITLE
로그인 화면 UI 구현 및 유효성 검사 추가

### ISSUE THREAD

**Issue by yeon-kk** [yeon-kk/wanted-pre-onboarding-frontend#6]
### 요구사항
- 회원가입과 로그인 페이지에 이메일과 비밀번호의 유효성 검사기능을 구현해주세요
- 두 페이지의 UI는 동일해도 무방합니다.

- 이메일 조건: @ 포함
- 비밀번호 조건: 8자 이상
- 이메일과 비밀번호의 유효성 검사 조건은 별도의 추가 조건 부여 없이 위의 조건대로만 진행해주세요 (e.g. 비밀번호 유효성 검사에 특수문자 포함 등의 새로운 조건을 추가하는 행위를 지양해주세요)
- 입력된 이메일과 비밀번호가 유효성 검사를 통과하지 못한다면 button에 disabled 속성을 부여해주세요
### 제안
- 회원가입 화면에서 수정 가능한 부분만 수정한다

### Tasks
- [x] 회원가입 UI에서 회원가입과 관련된 글자를 로그인으로 수정
- [x] '로그인' 버튼에 signin API 연동
- [x] 유효성 검사 함수 추가
